<a href="https://colab.research.google.com/github/WiktorT21/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [4]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

Tablice


In [9]:
x = np.array([1, 3])
x
print(x)
type(x)
x.size

[1 3]


2

In [13]:
x = np.array([[1, 2,], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [16]:
x = np.array(
    [[4, 3, 1],
     [3, 1, 2],
     [4, 1, 3],
     [4, 2, 1]]
)
x

array([[4, 3, 1],
       [3, 1, 2],
       [4, 1, 3],
       [4, 2, 1]])

In [19]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [20]:
B = np.array([1.0, 2.2, 3.1])
B.dtype

dtype('float64')

In [21]:
C = np.array([True, False])
C.dtype

dtype('bool')

Tworzenie Tablic


In [22]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [30]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
A.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach


In [37]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [38]:
A + B

array([6, 0, 7, 4])

In [44]:
np.add(A, B)

array([6, 0, 7, 4])

In [39]:
A - B

array([0, 2, 1, 0])

In [45]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [40]:
A * B

array([ 9, -1, 12,  4])

In [46]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [41]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [47]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [42]:
A + 3

array([6, 4, 7, 5])

In [43]:
A * 2

array([6, 2, 8, 4])

In [49]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array  ([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [50]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [51]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(80)

In [53]:
np.random.randn()

-0.3042487284387764

In [54]:
np.random.randn(10)

array([-2.00912898,  0.71010935, -1.41335408,  1.29135383, -2.51467938,
        0.22813947,  1.38534965, -0.80630385,  0.09709   ,  0.03296428])

In [55]:
np.random.randn(10, 4)

array([[ 1.37008878,  0.83279944, -1.75874245, -1.15525115],
       [ 0.22141654,  0.40315925, -0.92390074,  0.67589033],
       [-0.99064532,  0.14169272,  0.31929763, -0.75612596],
       [-1.53385386, -1.30669099, -0.52555296,  0.99191528],
       [ 1.36331037,  0.40097458, -0.21782636,  1.18917233],
       [-0.93144769, -2.096267  ,  0.74272152, -0.32275985],
       [-1.69625583, -0.0676374 ,  0.91504891,  0.14909565],
       [ 1.47218938,  0.49202907,  2.4362436 , -0.55376493],
       [-1.6219751 ,  0.7223067 ,  0.00565789,  0.65161615],
       [-0.39395694, -0.07151019, -0.17803059, -0.91916451]])

In [56]:
np.random.rand()

0.2231294818831644

In [57]:
np.random.randint(10)

4

In [59]:
np.random.randint(low=10, high=101, size=2)

array([76, 84])

In [69]:
np.random.choice([4, 2, 1, 4])

np.int64(4)

In [75]:
np.random.choice(['python', 'java', 'sql'])

np.str_('python')

In [76]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.random.shuffle(data)
data

array([7, 9, 8, 4, 2, 6, 3, 1, 5, 0])

Podstawowe funkcje

In [79]:
np.exp(1)

np.float64(2.718281828459045)

In [80]:
np.sqrt(9)

np.float64(3.0)

In [82]:
np.all([2, 3, 0])

np.False_

In [83]:
np.any([1, 2 , 1])

np.True_

In [85]:
bool(-1)

True

In [87]:
A = np.random.rand(5)
A

array([0.88861979, 0.65571853, 0.58043512, 0.71650754, 0.78462489])

In [88]:
np.argmax(A)

np.int64(0)

In [89]:
A[np.argmax(A)]

np.float64(0.888619789818052)

In [90]:
np.argmin(A)

np.int64(2)

In [91]:
np.argsort(A)

array([2, 1, 3, 4, 0])

In [92]:
np.max(A)

np.float64(0.888619789818052)

In [93]:
np.min(A)

np.float64(0.5804351168042831)

In [94]:
np.mean(A)

np.float64(0.7251811719113831)

In [95]:
np.median(A)

np.float64(0.7165075378755394)

In [96]:
np.std(A)

np.float64(0.1059220922420413)

Indeksowanie i wycinanie

In [97]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [98]:
A[2]

np.int64(2)

In [99]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [100]:
A[:2]

array([0, 1])

In [103]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [104]:
A[0]

array([0, 1, 2, 3, 4])

In [105]:
A[:, 0]

array([ 0,  5, 10, 15])

In [107]:
A[1, 3]

np.int64(8)

In [109]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [111]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [112]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [114]:
for row in A:
  print(row[0])

0
5
10
15


In [115]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [116]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [117]:
A.shape

(4, 5)

In [118]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [119]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [120]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [125]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [126]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [127]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [129]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [130]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])