<a href="https://colab.research.google.com/github/WiktorT21/data-science-bootcamp/blob/main/01_wprowadzenie/02_algerba_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Odległóść punktów

In [3]:
import numpy as np
np.__version__

'2.0.2'

In [7]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [8]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

In [9]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

np.float64(19.209372712298546)

In [10]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

np.float64(5.0)

In [13]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

np.float64(5.0990195135927845)

Mnożenie macierzy

In [4]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [6]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [7]:
X =np.array([[2, -1, 3],
             [3, 1, 0]])
Y=  np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [8]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik

In [12]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

np.float64(9.999999999999998)

In [13]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

np.int64(5)

In [15]:
np.eye(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [19]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [20]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [21]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [22]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [24]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

Funkcje statystyczne

In [25]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [26]:
price.sum()

np.float64(4650.1)

In [28]:
price.sum(axis=0) # suma kolumn poszczególnych

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [27]:
price.sum(axis=1) # suma wierszy poszczególnych

array([1049.7, 2049.4, 1551. ])

In [29]:
np.min(price)

np.float64(11.7)

In [31]:
np.max(price, axis=1)

array([1000., 2000., 1500.])

In [32]:
np.median(price)

np.float64(12.6)

In [35]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [36]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [37]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])